/**
 * Onboadring process
 */
export const ONBOARDING_SET_ANSWERS = "ONBOARDING_SET_ANSWERS";
export const ONBOARDING_SET_QUESTION_INDEX = "ONBOARDING_SET_QUESTION_INDEX";
export const ONBOARDING_SET_OLD_ANSWERS = "ONBOARDING_SET_OLD_ANSWERS";
export const ONBOARDING_RESET_ANSWERS = "ONBOARDING_RESET_ANSWERS";
